#!/usr/bin/env python

Import("env")
Import('env_modules')

env_lua = env_modules.Clone()

if not env.msvc:
    CXXFLAGS='-std=c++17'
else:
    CXXFLAGS='/std:c++17'

env_lua['CXXFLAGS'] = [CXXFLAGS]

Export('env_lua')

SConscript('luasrc/SCsub')

env_lua.add_source_files(env.modules_sources,'*.cpp')