# From https://github.com/MikeSchulze/gdUnit4/blob/master/.github/actions/install-godot/action.yml
name: install-godot-image
description: "Installs the Godot image"

inputs:
  godot-version:
    description: "The Godot Engine version to run"
    required: true

runs:
  using: composite
  steps:
    - name: Install Godot ${{ inputs.godot-version }}
      id : install
      continue-on-error: false
      env:
          GODOT_BIN: /usr/local/bin/godot/Godot.app/Contents/MacOS/Godot
      shell: bash
      run: |
        mkdir /usr/local/bin/godot
        wget https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_osx.universal.zip -P /usr/local/bin/godot
        unzip /usr/local/bin/godot/Godot_v${{ inputs.godot-version }}-stable_osx.universal.zip -d /usr/local/bin/godot/
        rm /usr/local/bin/godot/Godot_v${{ inputs.godot-version }}-stable_osx.universal.zip
        ls -lsR /usr/local/bin/godot
        chmod 770 /usr/local/bin/godot/Godot.app/Contents/MacOS/Godot