name: 🤖 Android
on:
  workflow_call:
    inputs:
      fullbuild:
        description: "Weather or not to build all targets"
        required: true
        type: boolean
        default: false
      
      godot_version:
        description: "Version of godot to be used"
        required: true
        type: string

env:
  BASE_BRANCH: main
  SCONSFLAGS: "production=yes extra_suffix=luaAPI"
  SCONS_CACHE_LIMIT: 7168
  GODOT_VERSION: ${{ inputs.godot_version }}-stable

jobs:
  android-builds:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.opts.name }}
    strategy:
      fail-fast: false
      matrix:
        opts:
          - name: Android Template (target=template_debug,arch=arm64)
            cache-name: android-debug-arm64
            artifact-name: android-templates
            build-options: "target=template_debug arch=arm64"
            should-run: true
          
          - name: Android Template (target=template_debug,arch=arm32)
            cache-name: android-debug-arm32
            artifact-name: android-templates
            build-options: "target=template_debug arch=arm32"
            should-run: ${{ inputs.fullbuild }}
          
          - name: Android Template (target=template_debug,arch=x86_64)
            cache-name: android-debug-x86_64
            artifact-name: android-templates
            build-options: "target=template_debug arch=x86_64"
            should-run: ${{ inputs.fullbuild }}
          
          - name: Android Template (target=template_debug,arch=x86_32)
            cache-name: android-debug-x86_32
            artifact-name: android-templates
            build-options: "target=template_debug arch=x86_32"
            should-run: ${{ inputs.fullbuild }}
          
          - name: Android Template (target=template_release,arch=arm64)
            cache-name: android-debug-arm64
            artifact-name: android-templates
            build-options: "target=template_release arch=arm64"
            should-run: ${{ inputs.fullbuild }}
          
          - name: Android Template (target=template_release,arch=arm32)
            cache-name: android-debug-arm32
            artifact-name: android-templates
            build-options: "target=template_release arch=arm32"
            should-run: ${{ inputs.fullbuild }}
          
          - name: Android Template (target=template_release,arch=x86_64)
            cache-name: android-debug-x86_64
            artifact-name: android-templates
            build-options: "target=template_release arch=x86_64"
            should-run: ${{ inputs.fullbuild }}
          
          - name: Android Template (target=template_release,arch=x86_32)
            cache-name: android-debug-x86_32
            artifact-name: android-templates
            build-options: "target=template_release arch=x86_32"
            should-run: ${{ inputs.fullbuild }}

        exclude:
          - {opts: {should-run: false}}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Load .scons_cache directory
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        working-directory: ./scripts
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=android ${{ matrix.opts.build-options }} ${{ env.SCONSFLAGS }}
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.opts.artifact-name}}
          path: scripts/godot/platform/android/java/lib/libs/*
